services:
  telegram-bridge:
    container_name: telegram-bridge
    restart: always
    image: telegram-bridge:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true