name: Gitleaks Security Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and run Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.23.3/gitleaks_8.23.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.23.3_linux_x64.tar.gz
          ./gitleaks detect --source . -v --config .gitleaks.toml
